import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import type { SymbolViewProps, SymbolWeight } from "expo-symbols";
import type { ComponentProps } from "react";
import type { OpaqueColorValue, StyleProp, TextStyle } from "react-native";

const MAPPING: Record<string, ComponentProps<typeof MaterialIcons>["name"]> = {
  "house.fill": "home",
  "house": "home",
  "paperplane.fill": "send",
  "chevron.left.forwardslash.chevron.right": "code",
  "chevron.right": "chevron-right",
  "chevron.left": "chevron-left",
  "chevron.up": "expand-less",
  "chevron.down": "expand-more",
  "bubble.left": "chat-bubble-outline",
  "bubble.left.fill": "chat-bubble",
  "plus": "add",
  "plus.circle.fill": "add-circle",
  "minus": "remove",
  "checkmark": "check",
  "checkmark.circle.fill": "check-circle",
  "checkmark.circle": "check-circle-outline",
  "xmark": "close",
  "xmark.circle": "cancel",
  "xmark.circle.fill": "cancel",
  "arrow.right": "arrow-forward",
  "arrow.left": "arrow-back",
  "arrow.up": "arrow-upward",
  "arrow.down": "arrow-downward",
  "arrow.up.arrow.down": "swap-vert",
  "arrow.down.doc.fill": "download",
  "arrow.up.arrow.down.circle.fill": "sync",
  "gear": "settings",
  "gearshape.fill": "settings",
  "person": "person",
  "person.fill": "person",
  "person.2.fill": "group",
  "person.3.fill": "groups",
  "person.badge.plus": "person-add",
  "person.badge.plus.fill": "person-add",
  "person.crop.circle.badge.exclamationmark": "account-circle",
  "list.bullet": "list",
  "magnifyingglass": "search",
  "trash": "delete",
  "trash.fill": "delete",
  "square.and.pencil": "edit",
  "square.and.arrow.up": "share",
  "bell": "notifications",
  "bell.fill": "notifications",
  "lock": "lock",
  "lock.open": "lock-open",
  "lock.shield.fill": "security",
  "eye": "visibility",
  "eye.slash": "visibility-off",
  "heart": "favorite",
  "heart.fill": "favorite",
  "star": "star",
  "star.fill": "star",
  "message": "mail",
  "phone": "phone",
  "camera": "camera",
  "photo": "photo",
  "video": "videocam",
  "music.note": "music-note",
  "globe": "public",
  "shield": "security",
  "shield.fill": "security",
  "cloud": "cloud",
  "cloud.download": "cloud-download",
  "cloud.upload": "cloud-upload",
  "folder": "folder",
  "folder.open": "folder-open",
  "doc.text": "article",
  "calendar": "calendar-today",
  "clock": "schedule",
  "clock.fill": "schedule",
  "location": "location-on",
  "cart": "shopping-cart",
  "creditcard": "payment",
  "info.circle": "info",
  "info.circle.fill": "info",
  "warning": "warning",
  "exclamationmark.triangle": "warning",
  "exclamationmark.triangle.fill": "warning",
  "questionmark.circle": "help",
  "questionmark.circle.fill": "help",
  "network": "network-wifi",
  "flame.fill": "local-fire-department",
  "bolt.fill": "bolt",
  "bolt.circle.fill": "offline-bolt",
  "chart.bar": "bar-chart",
  "chart.bar.fill": "bar-chart",
  "chart.line.uptrend.xyaxis": "trending-up",
  "square.stack.fill": "layers",
  "rectangle.portrait.and.arrow.right": "logout",
  "arrow.clockwise": "refresh",
  "paintbrush.fill": "brush",
  "moon.fill": "nightlight",
  "sun.max.fill": "light-mode",
  "lifepreserver.fill": "support",
  "lifepreserver": "support",
  "wifi": "wifi",
  "wifi.slash": "wifi-off",
  "play.fill": "play-arrow",
  "pause.fill": "pause",
  "stop.fill": "stop",
  "repeat": "repeat",
  "shuffle": "shuffle",
  "robot": "smart-toy",
  "cpu": "memory",
  "memorychip": "memory",
  "externaldrive": "storage",
  "key.fill": "key",
  "lightbulb.fill": "lightbulb",
  "antenna.radiowaves.left.and.right": "settings-input-antenna",
  "link": "link",
  "scissors": "content-cut",
  "doc.on.doc": "content-copy",
  "arrow.triangle.2.circlepath": "sync",
  "gobackward": "replay",
  "arrow.counterclockwise": "undo",
};

export function IconSymbol({
  name,
  size = 24,
  color,
  style,
}: {
  name: SymbolViewProps["name"];
  size?: number;
  color: string | OpaqueColorValue;
  style?: StyleProp<TextStyle>;
  weight?: SymbolWeight;
}) {
  const mappedName = MAPPING[name as string] || "help";
  return <MaterialIcons color={color} size={size} name={mappedName} style={style} />;
}
